# run: conda env create --file environment.yml
name: pybads-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy>=1.22.1
  - scipy>=1.7.3
  - matplotlib>=3.5.1
  - pytest>=6.2.5
  - pytest-mock>=3.6.1
  - pytest-rerunfailures>=10.2
