# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.8.3.dev18+g0652341.d20230607'
__version_tuple__ = version_tuple = (0, 8, 3, 'dev18', 'g0652341.d20230607')
